# Generated by Django 5.1 on 2024-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(default='Approved', max_length=100)),
            ],
            options={
                'db_table': 'FacultyModel',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rollid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('status', models.CharField(default='Approved', max_length=100)),
            ],
            options={
                'db_table': 'StudentModel',
            },
        ),
    ]
