# Generated by Django 5.1 on 2024-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshopname', models.CharField(max_length=100)),
                ('workshopdate', models.DateTimeField()),
                ('workshopimage', models.FileField(upload_to='static\\Workshop')),
                ('workshopfiles', models.FileField(upload_to='static\\WorkshopFiles')),
                ('dept', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'WorkshopModel',
            },
        ),
    ]
