# Generated by Django 5.1 on 2024-08-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workshopmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='desc',
            field=models.CharField(default='No Description', max_length=100),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='profile',
            field=models.FileField(default='No Profile', upload_to='static\\Student'),
        ),
    ]
