# Generated by Django 5.1 on 2024-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentmodel_desc_studentmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='desc',
            field=models.CharField(default='No Description', max_length=100),
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='profile',
            field=models.FileField(default='No Profile', upload_to='static\\Faculty'),
        ),
    ]
