# Generated by Django 5.1 on 2024-08-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_facultymodel_desc_facultymodel_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date', models.DateField(max_length=100)),
                ('rollid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('attendance', models.CharField(default='Absent', max_length=100)),
                ('ffname', models.CharField(max_length=100)),
                ('flname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AttendanceModel',
            },
        ),
    ]
