# Generated by Django 5.1 on 2024-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attendancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
