# Generated by Django 5.1 on 2024-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_attendancemodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('rollid', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('test1', models.IntegerField()),
                ('test2', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('finalsem', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentMarksModel',
            },
        ),
    ]
