# Generated by Django 5.1 on 2024-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentmarksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarksmodel',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmarksmodel',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
