# Generated by Django 5.1 on 2024-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_studentmarksmodel_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='marks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
