# Generated by Django 5.1 on 2024-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_studentmodel_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
