# Generated by Django 5.1 on 2024-09-05 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_studentmarksmodel_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='rollid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentmodel'),
        ),
    ]
