# Generated by Django 5.1 on 2024-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_studentmarksmodel_rollid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='rollid',
            field=models.CharField(max_length=100),
        ),
    ]
