# Generated by Django 5.1 on 2024-09-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_studentmarksmodel_rollid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='marks',
            new_name='s1',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='s3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='s4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='s5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
