# Generated by Django 5.1.1 on 2024-09-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_marks_studentmodel_s1_studentmodel_s3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
