from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('home/', views.home, name='home'),
    path('facilities/', views.facilities, name='facilities'),
    path('studentlogin/', views.studentlogin, name='studentlogin'),
    path('facultylogin/', views.facultylogin, name='facultylogin'),
    path('adminlogin/', views.adminlogin, name='adminlogin'),
    path('studentregister/', views.studentregister, name='studentregister'),
    path('facultyregister/', views.facultyregister, name='facultyregister'),
    path('logout/', views.logout, name='logout'),
    path('viewfaculty/', views.viewfaculty, name='viewfaculty'),
    path('updatefaculty/<int:id>/', views.updatefaculty, name='updatefaculty'),
    path('removefaculty/<int:id>/', views.removefaculty, name='removefaculty'),
    path('viewstudent/', views.viewstudent, name='viewstudent'),
    path('updatestudentprofile/', views.updatestudentprofile, name='updatestudentprofile'),
    path('removestudent/<int:id>/', views.removestudent, name='removestudent'),
    path('workshops/', views.workshops, name='workshops'),
    path('addworkshop/', views.addworkshop, name='addworkshop'),
    path('profile/', views.profile, name='profile'),
    path('downloadfile/<int:id>/', views.downloadfile, name='downloadfile'),
    path('updateworkshop/<int:id>/', views.updateworkshop, name='updateworkshop'),
    path('removeworkshop/<int:id>/', views.removeworkshop, name='removeworkshop'),
    path('attendance/', views.attendance, name='attendance'),
    path('submitattendance/', views.submitattendance, name='submitattendance'),
    path('myattendance/', views.myattendance, name='myattendance'),
    path('viewattendance/', views.viewattendance, name='viewattendance'),
    path('marks/', views.marks, name='marks'),
    path('uploadmarks/<str:rollid>/', views.uploadmarks, name='uploadmarks'),
    path('updatemarks/<str:rollid>/', views.updatemarks, name='updatemarks'),
    path('viewmarks/', views.viewmarks, name='viewmarks'),
    path('viewmymarks/', views.viewmymarks, name='viewmymarks'),
    path('viewstudentmarks/', views.viewstudentmarks, name='viewstudentmarks'),
    path('forgotpassword/',views.forgotpassword,name='forgotpassword'),
    path('resetpassword/',views.resetpassword,name='resetpassword'),

]
